CREATE TABLE Enclosure.TB_Enclosure --CREATION OF ENCLOSURE TABLE 
(
	Enclosure_ID INT PRIMARY KEY IDENTITY NOT NULL
	,Enclosure_Name VARCHAR(100) NOT NULL
	,Campus_ID INT NOT NULL
	,FOREIGN KEY(Campus_ID) REFERENCES Campus.TB_Campus(Campus_ID)
	,Erased BIT DEFAULT 0 NOT NULL 
)