CREATE SCHEMA CLASSROOM --CREATE SCHEMA CLASSROOM

CREATE TABLE CLASSROOM.TB_CLASSROOM --CREATE TABLE CLASSROOM AND ITS ATRIBUTE
(
CLASSROOM_ID VARCHAR(10),
CLASSROOM_NUMBER NUMERIC(2,0),
BUILDING_ID INT NOT NULL FOREIGN KEY REFERENCES BUILDING.TB_BUILDING 
)