CREATE TABLE CLASSROOM.TB_CLASSROOM_GROUP( --CREATE BUILDING TABLE AND ITS ATTRIBUTES
CLASSROOM_ID INT NOT NULL  FOREIGN KEY REFERENCES CLASSROOM.TB_CLASSROOM,
GROUP_ID INT NOT NULL FOREIGN KEY REFERENCES GROUP.TB_GROUP,
CG_YEAR DATE NULL,
CG_SEMESTER INTEGER
)