insert into [University].[TB_University] (University_Name) values ('Institute of Science and Technology');
insert into [University].[TB_University] (University_Name) values ('Kaunas University of Technology');
insert into [University].[TB_University] (University_Name) values ('College of Education Oju');
insert into [University].[TB_University] (University_Name) values ('University of New Hampshire');
insert into [University].[TB_University] (University_Name) values ('Universidad de San Miguel');
insert into [University].[TB_University] (University_Name) values ('Albany College of Pharmacy');
insert into [University].[TB_University] (University_Name) values ('Marquette University');
insert into [University].[TB_University] (University_Name) values ('University of Fiji');
insert into [University].[TB_University] (University_Name) values ('University of Tennessee - Chattanooga');
insert into [University].[TB_University] (University_Name) values ('Harbin University');