insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Oakwood Enclosure', 6);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Maple Grove Enclosure', 3);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Cedar Ridge Enclosure', 1);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Willow Creek Enclosure', 1);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Pinehurst Enclosure', 7);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Birchwood Enclosure', 7);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Sycamore Heights Enclosure', 2);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Aspen Valley Enclosure', 8);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Hickory Hollow Enclosure', 9);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Juniper Ridge Enclosure', 9);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Magnolia Gardens Enclosure', 4);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Cypress Point Enclosure', 5);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Spruce Meadows Enclosure', 10);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Elmwood Estates Enclosure', 1);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Redwood Ridge Enclosure', 2);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Oakwood Enclosure', 6);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Maple Grove Enclosure', 10);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Cedar Ridge Enclosure', 4);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Willow Creek Enclosure', 4);
insert into [Enclosure].[TB_Enclosure] (Enclosure_Name, Campus_ID) values ('Pinehurst Enclosure', 2);