insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Sunset Campus', 9);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Central Campus', 5);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Lakeview Campus', 9);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Willow Creek Campus', 6);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Meadowbrook Campus', 1);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Willow Creek Campus', 7);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('South Campus', 4);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Briarwood Campus', 1);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Briarwood Campus', 5);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Maplewood Campus', 9);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('South Campus', 3);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Highland Campus', 4);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Cedar Ridge Campus', 4);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Sunset Campus', 8);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Central Campus', 6);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('South Campus', 1);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('East Campus', 1);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Briarwood Campus', 2);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Sycamore Campus', 5);
insert into [Campus].[TB_Campus] (Campus_Name, University_ID) values ('Riverside Campus', 5);