CREATE SCHEMA CAMPUS --CREATE CAMPUS SCHEMA

CREATE TABLE CAMPUS.TB_Campus --CREATE CAMPUS TABLE AND ITS ATTRIBUTES
	Campus_ID INT PRIMARY KEY NOT NULL
	,Campus_Name VARCHAR(250) NOT NULL
	,University_ID INT NOT NULL 
	,FOREIGN KEY(University_ID) REFERENCES UNIVERSITY.TB_University
)
