CREATE TABLE CAMPUS.TB_Campus -- TABLE FOR CAMPUS AND ATTRIBUTES
(
	Campus_ID INT PRIMARY KEY NOT NULL
	,Campus_Name VARCHAR(250) NOT NULL
	,University_ID INT NOT NULL 
	,FOREIGN KEY(University_ID) REFERENCES UNIVERSITY.TB_University
	,Erased BIT DEFAULT 1 NOT NULL
)
