CREATE TABLE CAMPUS.TB_Campus
(
	Campus_ID INT PRIMARY KEY NOT NULL
	,Campus_Name VARCHAR(250) NOT NULL
	,University_ID INT NOT NULL 
	,FOREIGN KEY(University_ID) REFERENCES UNIVERSITY.TB_University
)
