CREATE SCHEMA CLASS_SCHEDULE --SCHEMA FOR CLASS_SCHEDULE

CREATE TABLE CLASS_SCHEDULE.TB_Class_Schedule --TABLE WHITH ITS ATTRIBUTES
(
	Schedule_ID INT PRIMARY KEY NOT NULL
	,Start_Time TIME 
	,End_Time TIME 
	,Day_Number INT 
)