CREATE TABLE Group_Class_Schedule --TABLE WITH ITS ATTRIBUTES
(
	Group_ID INT
	,FOREIGN KEY(Group_ID) REFERENCES GROUP.Group(Group_ID)
	,Schedule_ID INT
	,FOREIGN KEY(Schedule_ID) REFERENCES CLASS_SCHEDULE.Class_Schedule(Schedule_ID)
	,Erased BIT DEFAULT 1 NOT NULL
)