CREATE TABLE University.TB_University --CREATE TABLE UNIVERSITY AND ITS ATTRIBUTES
(
	University_ID INT PRIMARY KEY IDENTITY NOT NULL 
	,University_Name VARCHAR(100) NOT NULL
	,Erased BIT DEFAULT 1 NOT NULL
)


