CREATE SCHEMA UNIVERSITY --CREATE SCHEMA FOR UNIVERSITY


CREATE TABLE UNIVERSITY.TB_University --CREATE TABLE UNIVERSITY AND ITS ATTRIBUTES
(
	University_ID INT PRIMARY KEY NOT NULL --ID FOR UNIVERSITY
	,University_Name VARCHAR(50) --NAME
)






