CREATE SCHEMA SCHOOL --CREATE SCHOOL SCHEMA 
CREATE TABLE SCHOOL.TB_SCHOOLS  --CREATE SCHOOL TABLE AND ITS ATTRIBUTES
(
ID_SCHOOLS INT NOT NULL PRIMARY KEY,
NAME_SCHOOLS VARCHAR(20),
DESCRIPTION_SCHOOL VARCHAR(100)
)